export default {
	bounce : '弹跳',
	flash: '闪烁',
	pulse: '脉动',
	// rubberBand: '紧绷',
	shake: '抖动',
	swing: '悬挂',
	tada: '跷跷板',
	wobble: '摇摆',
	// jello: '凝聚',
	bounceIn: '跳入1',
	bounceInDown: '跳入2',
	bounceInLeft: '跳入3',
	bounceInRight: '跳入4',
	bounceInUp: '跳入5',
	fadeIn: '淡入1',
	fadeInDown: '淡入2',
	fadeInDownBig: '淡入3',
	fadeInLeft: '淡入4',
	fadeInLeftBig: '淡入5',
	fadeInRight: '淡入6',
	fadeInRightBig: '淡入7',
	fadeInUp: '淡入8',
	fadeInUpBig: '淡入9',
	flip: '翻转',
	flipInX: 'X翻入',
	flipInY: 'Y翻入',
	lightSpeedIn: '光速入',
	rotateIn: '旋转入1',
	rotateInDownLeft: '旋转入2',
	rotateInDownRight: '旋转入3',
	rotateInUpLeft: '旋转入4',
	rotateInUpRight: '旋转入5',
	// slideInUp: '推入1',
	// slideInDown: '推入2',
	// slideInLeft: '推入3',
	// slideInRight: '推入4',
	// zoomIn: '放大1',
	// zoomInDown: '放大2',
	// zoomInLeft: '放大3', 
	// zoomInRight: '放大4', 
	// zoomInUp: '放大5',
	hinge: '掉了',
	rollIn: '转入',
}
// 后备
export var animateOut = {
	bounceOut: '跳出1',
	bounceOutDown: '跳出2',
	bounceOutLeft: '跳出3',
	bounceOutRight: '跳入4',
	bounceOutUp: '跳入5',
	fadeOut: '淡出1',	
	fadeOutDown: '淡出2',
	fadeOutDownBig: '淡出3',
	fadeOutLeft: '淡出4',
	fadeOutLeftBig: '淡出5',
	fadeOutRight: '淡出6',
	fadeOutRightBig: '淡出7',
	fadeOutUp: '淡出8',
	fadeOutUpBig: '淡出9',
	flipOutX: '翻出X',
	flipOutY: '翻出Y',
	lightSpeedOut: '光速出',
	rotateOut: '旋转出1',
	rotateOutDownLeft: '旋转出2',
	rotateOutDownRight: '旋转出3',
	rotateOutUpLeft: '旋转出4',
	rotateOutUpRight: '旋转出5',
	// slideOut: '推出1',
	// slideOutDown: '推出2',
	// slideOutLeft: '推出3',
	// // slideOutRight: '推出4',
	// zoomOut: '缩小1',
	// zoomOutDown: '缩小2',
	// zoomOutLeft: '缩小3',
	// zoomOutRight: '缩小4', 
	// zoomOutUp: '缩小5',
	rollOut: '转出'
}